name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0,12 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: vavakado
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Jerusalem
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: 8fzhm30kehsrytx64kpfld6m8
          repositories_batch: 100
